-- =========================================
-- CREATE SURVEY TABLE
-- =========================================

create table survey_responses (

    id bigint generated by default as identity
        primary key,

    deforestation text not null,

    sdg_awareness text not null,

    main_issue text not null,

    participation text not null,

    preferred_action text not null,

    submitted_at timestamp with time zone
        default now()

);


-- =========================================
-- ENABLE ROW LEVEL SECURITY
-- =========================================

alter table survey_responses
enable row level security;


-- =========================================
-- ALLOW ANONYMOUS USERS TO SUBMIT
-- =========================================

create policy "Allow anonymous survey submissions"

on survey_responses

for insert

to anon

with check (true);


-- =========================================
-- ALLOW ANONYMOUS USERS TO VIEW RESULTS
-- =========================================

create policy "Allow anonymous users to read survey data"

on survey_responses

for select

to anon

using (true);